plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.google.devtools.ksp'
}

android {
    final sdk = rootProject.ext.sdk

    compileSdk sdk.compileSdk

    defaultConfig {
        applicationId "dev.bipin.test"
        minSdkVersion sdk.minSdk
        targetSdkVersion sdk.targetSdk
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        signingConfig signingConfigs.debug
    }

    signingConfigs {
        debug {
            // Use default debug certificate provided in Android SDK
        }

        release {
            def keystorePropertiesFile = rootProject.file("release.properties")
            if (keystorePropertiesFile.exists()) {
                def keystoreProperties = new Properties()
                keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

                keyAlias keystoreProperties["keyAlias"]
                keyPassword keystoreProperties["keyPassword"]
                storeFile file(keystoreProperties["storeFile"])
                storePassword keystoreProperties["storePassword"]
            }
        }
    }


    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            shrinkResources false
            firebaseCrashlytics {
                mappingFileUploadEnabled false
            }
        }

        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            firebaseCrashlytics {
                mappingFileUploadEnabled true
            }
        }
    }

    flavorDimensions += "env"

    productFlavors {
        local {
            dimension "env"
            buildConfigField("String", "API_BASE_URL", "\"http://192.168.1.222:3000/api/\"")
            buildConfigField("String", "X_API_KEY", "\"YEFYhOur0UVjnNZsUo0LmjZOSXZNu0N0MoYgu\"")
            buildConfigField("String", "JUNE_MOBILE_APP_WRITE_KEY", "\"yVpRfVFVeXdBu5Ve\"")
            buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"AIzaSyB7eAY5FBqoybCgyriaRufVkcYEf-3T9nI\"")
            buildConfigField("String", "AWS_S3_BUCKET_URL", "\"https://hammr-customer-files-staging.s3.us-west-1.amazonaws.com/\"")
            buildConfigField("String", "AWS_S3_BUCKET_NAME", "\"hammr-customer-files-staging\"")

        }

        dev {
            dimension "env"
            buildConfigField("String", "API_BASE_URL", "\"https://punchout.hammr.com/api/\"")
            buildConfigField("String", "X_API_KEY", "\"YEFYhOur0UVjnNZsUo0LmjZOSXZNu0N0MoYgu\"")
            buildConfigField("String", "JUNE_MOBILE_APP_WRITE_KEY", "\"yVpRfVFVeXdBu5Ve\"")
            buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"AIzaSyB7eAY5FBqoybCgyriaRufVkcYEf-3T9nI\"")
            buildConfigField("String", "AWS_S3_BUCKET_URL", "\"https://hammr-customer-files-staging.s3.us-west-1.amazonaws.com/\"")
            buildConfigField("String", "AWS_S3_BUCKET_NAME", "\"hammr-customer-files-staging\"")
        }

        prod {
            dimension "env"
            buildConfigField("String", "API_BASE_URL", "\"https://api.hammr.com/api/\"")
            buildConfigField("String", "X_API_KEY", "\"YEFYhOur0UVjnNZsUo0LmjZOSXZNu0N0MoYgu\"")
            buildConfigField("String", "JUNE_MOBILE_APP_WRITE_KEY", "\"RHpV4ukYarvpktEQ\"")
            buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"AIzaSyB7eAY5FBqoybCgyriaRufVkcYEf-3T9nI\"")
            buildConfigField("String", "AWS_S3_BUCKET_URL", "\"https://hammr-customer-files-production.s3.us-west-1.amazonaws.com/\"")
            buildConfigField("String", "AWS_S3_BUCKET_NAME", "\"hammr-customer-files-production\"")
        }
    }

    lint {
        disable 'NullSafeMutableLiveData'
        abortOnError true
        checkReleaseBuilds true
    }

    kotlinOptions {
        jvmTarget = "17"
        freeCompilerArgs = ['-Xjvm-default=all-compatibility']
    }

    packagingOptions {
        resources.excludes.add("META-INF/*")
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'

    implementation "androidx.appcompat:appcompat:1.2.0"
    implementation "androidx.constraintlayout:constraintlayout:2.0.4"
    implementation "androidx.coordinatorlayout:coordinatorlayout:1.1.0"

    implementation "androidx.vectordrawable:vectordrawable:1.1.0"
    implementation "com.google.android.material:material:1.3.0-alpha04"

    implementation "androidx.activity:activity-ktx:1.1.0"
    implementation "androidx.fragment:fragment-ktx:1.3.0-beta02"

    implementation "androidx.cardview:cardview:1.0.0"

    implementation "androidx.viewpager2:viewpager2:1.1.0-alpha01"

    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}
